#!/bin/bash


BIN_DIR="$( cd "$( dirname "$0"  )" && pwd  )"
cd ../;
#mkdir lib;
BASE_DIR=` cd ${BIN_DIR}; cd ../../../../; pwd`
LIB_DIR=` cd ${BIN_DIR}; cd ../lib; pwd `
READER_DIR=` cd ${BIN_DIR}; cd ../plugin/reader; pwd `
WRITER_DIR=` cd ${BIN_DIR}; cd ../plugin/writer; pwd `
readers=("linkoopdbreader" "mysqlreader" "postgresqlreader" "txtfilereader" "excelreader" "oraclereader")
writers=('linkoopdbwriter' 'mysqlwriter' 'postgresqlwriter' 'txtfilewriter' 'excelwriter' 'oraclewriter')

cd ${BASE_DIR}
source ~/.bash_profile
mvn -U clean package assembly:assembly -Dmaven.test.skip=true

readers_url='target/datax/plugin/reader'
writers_url='target/datax/plugin/writer'
echo ${READER_DIR}

for var in ${readers[@]}
do
  cd ${BASE_DIR}/${var}/${readers_url}/${var}
  ln -sf ` pwd ` ${READER_DIR}
done

for var in ${writers[@]}
do
  cd ${BASE_DIR}/${var}/${writers_url}/${var}
  cp -R libs/* ${LIB_DIR}
#  rm -rf libs
  ln -sf ` pwd ` ${WRITER_DIR}
done

cp ${BASE_DIR}/plugin-linkoopdb-util/target/plugin-linkoopdb-util-0.0.1-SNAPSHOT.jar ${BASE_DIR}/target/datax/datax/lib/

cd ${BASE_DIR}
sudo find ./ -name ".DS_Store" -depth -exec rm -rf {} \;

cd ${BASE_DIR}/target/datax
tar -czf linkoopdb_trans.tar.gz datax
scp ./linkoopdb_trans.tar.gz auxo@192.168.1.133:/home/auxo/share-site/dist/linkoopdb-tools/2.3.0

